# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import decimal
import enum
import typing
from symbolica.community.idenso import (
    ColorCasimirSettings,
    ColorSimplifySettings,
    CookSettings,
    GammaSimplifySettings,
    SchoonschipSettings,
)
from symbolica.core import (
    Condition,
    Expression,
    FormattedOutput,
    HeldExpression,
    PatternRestriction,
    Transformer,
)

AUTO: _AutoIndex
_: _AutoIndex

@typing.final
class BroadcastFunction:
    r"""
    A unary Symbolica function whose action is broadcast over tensor entries.
    """
    def __new__(
        cls,
        name: builtins.str,
        *,
        is_symmetric: typing.Optional[builtins.bool] = None,
        is_antisymmetric: typing.Optional[builtins.bool] = None,
        is_cyclesymmetric: typing.Optional[builtins.bool] = None,
        is_linear: typing.Optional[builtins.bool] = None,
        is_flat: typing.Optional[builtins.bool] = None,
        is_scalar: typing.Optional[builtins.bool] = None,
        is_real: typing.Optional[builtins.bool] = None,
        is_integer: typing.Optional[builtins.bool] = None,
        is_positive: typing.Optional[builtins.bool] = None,
        tags: typing.Optional[typing.Sequence[builtins.str]] = None,
        aliases: typing.Optional[typing.Sequence[builtins.str]] = None,
        normalization: typing.Optional[Transformer] = None,
        print: typing.Optional[typing.Any] = None,
        derivative: typing.Optional[typing.Any] = None,
        series: typing.Optional[typing.Any] = None,
        eval: typing.Optional[typing.Any] = None,
        data: typing.Optional[
            Expression
            | int
            | str
            | float
            | builtins.complex
            | str
            | dict
            | list
            | bytes
        ] = None,
    ) -> BroadcastFunction: ...
    @staticmethod
    def conj() -> BroadcastFunction:
        r"""
        Return Spenso's registered complex-conjugation broadcast function.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def to_expression(self) -> Expression: ...
    def has_tag(self, tag: builtins.str) -> builtins.bool: ...
    def get_tags(self) -> builtins.list[builtins.str]: ...
    @typing.overload
    def __call__(self, arg: Tensor | TensorNetwork) -> TensorNetwork:
        r"""
        Apply this unary function lazily to a concrete tensor or tensor network.
        """
    @typing.overload
    def __call__(self, arg: TensorExpression) -> TensorExpression:
        r"""
        Apply this unary function elementwise, preserving a structured interface.
        """
    @typing.overload
    def __call__(
        self, arg: Expression | int | str | float | builtins.complex
    ) -> Expression:
        r"""
        Apply this unary function to an ordinary scalar expression.
        """

@typing.final
class CompiledTensorEvaluator:
    r"""
    A compiled and optimized evaluator for maximum performance tensor evaluation.

    This class wraps a compiled C++ shared library for extremely fast numerical
    evaluation of tensor expressions. It only supports complex-valued evaluation
    as this is the most general case.

    A compiled and optimized evaluator for maximum performance tensor evaluation.

    This class wraps a compiled C++ shared library for extremely fast numerical
    evaluation of tensor expressions. It only supports complex-valued evaluation
    as this is the most general case.

    Create instances using the `TensorEvaluator.compile()` method.

    Examples
    --------
    >>> compiled = evaluator.compile("eval_func", "code.cpp", "lib")
    >>> results = compiled.evaluate_complex(large_input_batch)
    """
    def evaluate_complex(
        self, inputs: typing.Sequence[typing.Sequence[builtins.complex]]
    ) -> builtins.list[Tensor]:
        r"""
        Evaluate the tensor expression for multiple complex-valued parameter inputs.

        Evaluate the tensor expression for multiple complex-valued parameter inputs.

        Uses the compiled C++ code for maximum performance evaluation with complex numbers.

        Parameters
        ----------
        inputs : list of list of complex
            List of parameter value lists, where each inner list contains
            complex values for all parameters in the same order as specified
            when creating the original evaluator

        Returns
        -------
        list of Tensor
            List of evaluated tensors, one for each input parameter set

        Examples
        --------
        >>> complex_inputs = [
        ...     [1.0+2.0j, 3.0+0.0j],
        ...     [0.0+1.0j, 2.0+1.0j]
        ... ]
        >>> results = compiled_evaluator.evaluate_complex(complex_inputs)
        """

@typing.final
class Representation:
    r"""
    A representation in the sense of group representation theory for tensor indices.

    Representations define the transformation properties of tensor indices under group operations.
    They specify the dimension and duality structure, determining which indices can contract.

    Key concepts:
    - **Self-dual**: Indices can contract with other indices of the same representation
    - **Dualizable**: Indices can only contract with their dual representation
    - **Dimension**: Size of the representation space

    Predefined representations are available as class methods:
    - `Representation.euc(d)`: Euclidean space (self-dual)
    - `Representation.mink(d)`: Minkowski space (self-dual)
    - `Representation.bis(d)`: Bispinor (self-dual)
    - `Representation.cof(d)`: Color fundamental (dualizable)
    - `Representation.coad(d)`: Color adjoint (self-dual)
    - `Representation.cos(d)`: Color sextet (dualizable)

    # Examples:
    ```python
    from symbolica.community.spenso import Representation

    # Standard representations
    euclidean = Representation.euc(4)      # 4D Euclidean
    lorentz = Representation.mink(4)       # 4D Minkowski
    color = Representation.cof(3)          # SU(3) fundamental
    adjoint = Representation.coad(8)       # SU(3) adjoint

    # Custom representation
    custom = Representation("MyRep", 5, is_self_dual=True)

    # Create slots with indices
    mu_slot = euclidean('mu')              # Euclidean index μ
    a_slot = color('a')                    # Color index a

    # Generate metric tensors
    metric = euclidean.g('mu', 'nu')       # g_μν
    ```
    """
    @property
    def dimension(self) -> Expression:
        r"""
        Return the dimension carried by this representation.
        """
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    @typing.overload
    def __call__(self, aind: builtins.int | Expression | str) -> Slot:
        r"""
        Create a slot from this representation, by specifying an index.

        Parameters
        ----------
        aind : int, str, or Symbol
            The index specification

        Returns
        -------
        Slot
            A new Slot object with the specified index

        Examples
        --------
        >>> from symbolica.community.spenso import Representation
        >>> import symbolica as sp
        >>> rep = Representation.euc(3)
        >>> slot1 = rep('mu')
        >>> slot2 = rep(1)
        >>> slot3 = rep(sp.S('nu'))
        """
    @typing.overload
    def __call__(self, aind: Expression) -> Expression | Slot:
        r"""
        Create a slot or symbolic expression from this representation.

        Parameters
        ----------
        aind : Expression
            The index specification (Expression creates symbolic representation)

        Returns
        -------
        Expression
            A symbolic expression representing this representation

        Examples
        --------
        >>> from symbolica.community.spenso import Representation
        >>> import symbolica as sp
        >>> rep = Representation.euc(3)
        >>> expr = rep(sp.E("cos(x)"))
        """
    def __new__(
        cls,
        name: builtins.str,
        dimension: builtins.int | Expression | str,
        is_self_dual: builtins.bool = ...,
    ) -> Representation:
        r"""
        Create and register a new representation with specified properties.

        # Parameters:
        - name: String name for the representation
        - dimension: Size of the representation (int or symbolic)
        - is_self_dual: If True, creates self-dual representation; if False, creates dualizable pair

        # Examples:
        ```python
        from symbolica.community.spenso import Representation
        import symbolica as sp

        # Self-dual representation (indices contract with themselves)
        euclidean = Representation("Euclidean", 4, is_self_dual=True)

        # Dualizable representation (needs dual partner for contraction)
        vector_up = Representation("VectorUp", 4, is_self_dual=False)

        # Symbolic dimension
        n = sp.S('n')
        general = Representation("General", n, is_self_dual=True)
        ```
        """
    def dual(self) -> Representation: ...
    def casimir(
        self, degree: Expression | int | str | float | builtins.complex = ...
    ) -> Expression:
        r"""
        Build the degree-k Casimir eigenvalue for this representation.
        """
    def dynkin_index(
        self, degree: Expression | int | str | float | builtins.complex = ...
    ) -> Expression:
        r"""
        Build the degree-k Dynkin index for this representation.
        """
    def gram(
        self,
        degree: Expression | int | str | float | builtins.complex,
        other: typing.Optional[Representation] = None,
    ) -> Expression:
        r"""
        Build a degree-k Gram invariant with another representation.

        If `other` is omitted, both sides use this representation.
        """
    def g(
        self, i: builtins.int | Expression | str, j: builtins.int | Expression | str
    ) -> TensorExpression:
        r"""
        Create a metric tensor for this representation.

        # Parameters:
        - i: First index
        - j: Second index

        # Examples:
        ```python
        rep = Representation.mink(4)
        metric = rep.g('mu', 'nu')  # Minkowski metric g_μν
        ```
        """
    def flat(
        self, i: builtins.int | Expression | str, j: builtins.int | Expression | str
    ) -> TensorExpression:
        r"""
        Create a musical isomorphism tensor for this representation.

        # Parameters:
        - i: First index
        - j: Second index

        # Examples:
        ```python
        rep = Representation.mink(4)
        flat = rep.flat('mu', 'nu')  # Flat isomorphism ♭_μν
        ```
        """
    def id(
        self, i: builtins.int | Expression | str, j: builtins.int | Expression | str
    ) -> TensorExpression:
        r"""
        Create an identity tensor for this representation.

        # Parameters:
        - i: First index
        - j: Second index

        # Examples:
        ```python
        rep = Representation.cof(3)
        identity = rep.id('a', 'b')  # Color identity δ_ab
        ```
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def to_expression(self) -> Expression:
        r"""
        Convert the representation to a symbolic expression.
        """
    @staticmethod
    def bis(dimension: builtins.int | Expression | str) -> Representation:
        r"""
        Create a bispinor representation.

        # Parameters:
        - dimension: The dimension of the bispinor space
        """
    @staticmethod
    def euc(dimension: builtins.int | Expression | str) -> Representation:
        r"""
        Create a Euclidean space representation.

        # Parameters:
        - dimension: The dimension of the Euclidean space
        """
    @staticmethod
    def mink(dimension: builtins.int | Expression | str) -> Representation:
        r"""
        Create a Minkowski space representation.

        # Parameters:
        - dimension: The dimension of the Minkowski space
        """
    @staticmethod
    def cof(dimension: builtins.int | Expression | str) -> Representation:
        r"""
        Create a color fundamental representation.

        # Parameters:
        - dimension: The dimension of the color group (e.g., 3 for SU(3))
        """
    @staticmethod
    def coad(dimension: builtins.int | Expression | str) -> Representation:
        r"""
        Create a color adjoint representation.

        # Parameters:
        - dimension: The dimension of the adjoint representation (e.g., 8 for SU(3))
        """
    @staticmethod
    def cos(dimension: builtins.int | Expression | str) -> Representation:
        r"""
        Create a color sextet representation.

        # Parameters:
        - dimension: The dimension of the sextet representation (e.g., 6 for SU(3))
        """

@typing.final
class Slot:
    r"""
    A tensor index slot combining a representation with an abstract index.

    Slots are the building blocks for tensor structures, pairing a representation
    (which defines transformation properties) with an abstract index identifier.
    Slots with matching representations and indices can be contracted.

    # Examples:
    ```python
    from symbolica.community.spenso import Slot, Representation
    import symbolica as sp

    # Create representation and slots
    rep = Representation.euc(3)
    slot1 = rep('mu')           # Slot with string index
    slot2 = rep(1)              # Slot with integer index
    slot3 = rep(sp.S('nu'))     # Slot with symbolic index

    # Create custom slot
    custom_slot = Slot("MyRep", 4, 'alpha', dual=False)

    # Use in tensor structures
    from symbolica.community.spenso import TensorName
    tensor_expression = TensorName("T")(slot1, slot2)
    ```
    """
    def __eq__(self, other: builtins.object) -> builtins.bool: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def dual(self) -> Slot: ...
    def __new__(
        cls,
        name: builtins.str,
        dimension: builtins.int,
        aind: builtins.int | Expression | str,
        dual: builtins.bool = ...,
    ) -> Slot:
        r"""
        Create a new slot with a custom representation and index.

        # Parameters:
        - name: String name for the representation
        - dimension: Size of the representation space
        - aind: The abstract index (int, str, or Symbol)
        - dual: If True, creates dualizable representation; if False, self-dual

        # Examples:
        ```python
        from symbolica.community.spenso import Slot
        import symbolica as sp

        # Self-dual slot
        euclidean_slot = Slot("Euclidean", 4, 'mu', dual=False)

        # Dualizable slot
        vector_slot = Slot("Vector", 4, 'nu', dual=True)

        # With symbolic index
        sym_index = sp.S('alpha')
        symbolic_slot = Slot("Custom", 3, sym_index, dual=False)
        ```
        """
    def to_expression(self) -> Expression:
        r"""
        Convert the slot to a symbolic expression.

        # Examples:
        ```python
        rep = Representation.euc(3)
        slot = rep('mu')
        expr = slot.to_expression()  # Symbolic representation of the slot
        ```
        """

@typing.final
class Tensor:
    r"""
    A tensor class that can be either dense or sparse with flexible data types.

    The tensor can store data as floats, complex numbers, or symbolic expressions.
    Tensors have an associated structure that defines their shape and index properties.

    Examples
    --------
    >>> from symbolica.community.spenso import Tensor, TensorName, Representation
    >>> rep = Representation.euc(4)
    >>> structure = TensorName.vector("v")(rep("mu"))
    >>> data = [1.0, 2.0, 3.0, 4.0]
    >>> tensor = Tensor.dense(structure, data)
    >>> sparse_tensor = Tensor.sparse(structure, float)
    """
    def structure(self) -> TensorExpression: ...
    def with_name(
        self, name: TensorName | builtins.str | Expression | TensorExpression
    ) -> Tensor:
        r"""
        Return a copy with a new data identity while preserving its expression and interface.
        """
    @staticmethod
    def sparse(structure: TensorExpression, type_info: type) -> Tensor:
        r"""
        Create a new sparse empty tensor with the given structure and data type.

        Parameters
        ----------
        structure : TensorExpression
            A named expression with unresolved, explicit, or mixed interface ports
        type_info : type
            The data type - either `float` or `Expression` class

        Returns
        -------
        Tensor
            A new sparse tensor with all elements initially zero

        Examples
        --------
        >>> from symbolica.community.spenso import Tensor, TensorName, Representation
        >>> rep = Representation.euc(3)
        >>> structure = TensorName("T")(rep, rep)
        >>> sparse_float = Tensor.sparse(structure, float)
        >>> sparse_sym = Tensor.sparse(structure, symbolica.Expression)
        """
    @staticmethod
    def dense(
        structure: TensorExpression,
        data: typing.Sequence[Expression]
        | typing.Sequence[builtins.float]
        | typing.Sequence[builtins.complex],
    ) -> Tensor:
        r"""
        Create a new dense tensor with the given structure and data.

        Parameters
        ----------
        structure : TensorExpression
            A named expression with unresolved, explicit, or mixed interface ports
        data : list of float, complex, or Expression
            The tensor data in row-major order

        Returns
        -------
        Tensor
            A new dense tensor with the specified data

        Examples
        --------
        >>> from symbolica import S
        >>> from symbolica.community.spenso import Tensor, TensorName, Representation
        >>> rep = Representation.euc(2)
        >>> structure = TensorName("T")(rep("mu"), rep("nu"))
        >>> data = [1.0, 2.0, 3.0, 4.0]
        >>> tensor = Tensor.dense(structure, data)
        >>> x, y = S("x", "y")
        >>> sym_data = [x, y, x * y, x + y]
        >>> sym_tensor = Tensor.dense(structure, sym_data)
        """
    def to_dense(self) -> None:
        r"""
        Convert this tensor to dense storage format.

        Convert this tensor to dense storage format.

        Converts sparse tensors to dense format in-place. Dense tensors are unchanged.
        This allocates memory for all tensor elements.

        Examples
        --------
        >>> from symbolica.community.spenso import Tensor, TensorName, Representation
        >>> rep = Representation.euc(4)
        >>> structure = TensorName.vector("v")(rep("mu"))
        >>> tensor = Tensor.sparse(structure, float)
        >>> tensor[0] = 1.0
        >>> tensor.to_dense()
        """
    def to_sparse(self) -> None:
        r"""
        Convert this tensor to sparse storage format.

        Convert this tensor to sparse storage format.

        Converts dense tensors to sparse format in-place, only storing non-zero elements.
        This can save memory for tensors with many zero elements.

        Examples
        --------
        >>> from symbolica.community.spenso import Tensor, TensorName, Representation
        >>> rep = Representation.euc(2)
        >>> structure = TensorName("T")(rep("mu"), rep("nu"))
        >>> data = [1.0, 0.0, 0.0, 2.0]
        >>> tensor = Tensor.dense(structure, data)
        >>> tensor.to_sparse()
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def format_tensor(self, show_dimensions: builtins.bool = ...) -> builtins.str:
        r"""
        Format this concrete tensor using compact Spenso notation.
        """
    def to_typst(self, show_dimensions: builtins.bool = ...) -> builtins.str:
        r"""
        Format this concrete tensor as Typst math source.
        """
    def formatted(self, show_dimensions: builtins.bool = ...) -> FormattedOutput:
        r"""
        Build Symbolica's rich display wrapper for this concrete tensor.
        """
    def _repr_html_(self) -> typing.Optional[builtins.str]: ...
    def _repr_latex_(self) -> typing.Optional[builtins.str]: ...
    def _repr_pretty_(self, pretty: typing.Any, cycle: builtins.bool) -> None: ...
    def __len__(self) -> builtins.int: ...
    @typing.overload
    def __getitem__(
        self, item: builtins.slice | builtins.int | builtins.list[builtins.int]
    ) -> typing.Any: ...
    @typing.overload
    def __getitem__(
        self, item: builtins.slice
    ) -> builtins.list[Expression | builtins.complex | float]:
        r"""
        Get tensor elements at the specified range of indices.

        Parameters
        ----------
        item : slice
            Slice object defining the range of indices

        Returns
        -------
        list of float, complex, or Expression
            The tensor elements at the specified range
        """
    @typing.overload
    def __getitem__(
        self, item: typing.Sequence[builtins.int] | builtins.int
    ) -> Expression | builtins.complex | float:
        r"""
        Get tensor element at the specified index or indices.

        Parameters
        ----------
        item : int or list of int
            Index specification (int for flat index, list of int for coordinates)

        Returns
        -------
        float, complex, or Expression
            The tensor element at the specified index
        """
    @typing.overload
    def __setitem__(self, item: typing.Any, value: typing.Any) -> None:
        r"""
        Set tensor element(s) at the specified index or indices.

        Parameters
        ----------
        item : int or list of int
            Index specification (int for flat index, list of int for coordinates)
        value : float, complex, or Expression
            The value to set

        Examples
        --------
        >>> from symbolica.community.spenso import Tensor, TensorName, Representation
        >>> rep = Representation.euc(2)
        >>> structure = TensorName("T")(rep("mu"), rep("nu"))
        >>> tensor = Tensor.sparse(structure, float)
        >>> tensor[0] = 4.0
        >>> tensor[1, 1] = 1.0
        """
    @typing.overload
    def __setitem__(
        self,
        item: builtins.int | typing.Sequence[builtins.int],
        value: Expression | builtins.complex | float,
    ) -> None:
        r"""
        Set tensor element at the specified index.

        Parameters
        ----------
        item : int or list of int
            Index specification (int for flat index, list of int for coordinates)
        value : float, complex, or Expression
            The value to set

        Examples
        --------
        >>> from symbolica.community.spenso import Tensor, TensorName, Representation
        >>> rep = Representation.euc(2)
        >>> structure = TensorName("T")(rep("mu"), rep("nu"))
        >>> tensor = Tensor.sparse(structure, float)
        >>> tensor[0] = 1.0
        >>> tensor[1, 1] = 2.0
        """
    def evaluator(
        self,
        constants: typing.Mapping[Expression, Expression],
        funs: typing.Mapping[
            tuple[Expression, builtins.str, typing.Sequence[Expression]], Expression
        ],
        params: typing.Sequence[Expression],
        iterations: builtins.int = ...,
        n_cores: builtins.int = ...,
        verbose: builtins.bool = ...,
    ) -> TensorEvaluator:
        r"""
        Create an optimized evaluator for symbolic tensor expressions.

        Create an optimized evaluator for symbolic tensor expressions.

        Compiles the symbolic expressions in this tensor into an optimized evaluation tree
        that can efficiently compute numerical values for different parameter inputs.

        Parameters
        ----------
        constants : dict
            Dict mapping symbolic expressions to their constant numerical values
        funs : dict
            Dict mapping function signatures to their symbolic definitions
        params : list of Expression
            List of symbolic parameters that will be varied during evaluation
        iterations : int, optional
            Number of optimization iterations for Horner scheme (default: 100)
        n_cores : int, optional
            Number of CPU cores to use for optimization (default: 4)
        verbose : bool, optional
            Whether to print optimization progress (default: False)

        Returns
        -------
        TensorEvaluator
            An optimized evaluator for efficient numerical evaluation

        Examples
        --------
        >>> from symbolica import S
        >>> from symbolica.community.spenso import Tensor, TensorName, Representation
        >>> x, y = S("x", "y")
        >>> rep = Representation.euc(2)
        >>> structure = TensorName.vector("v")(rep("mu"))
        >>> tensor = Tensor.dense(structure, [x * y, x + y])
        >>> evaluator = tensor.evaluator(constants={}, funs={}, params=[x, y], iterations=50)
        >>> results = evaluator.evaluate_complex([[1.0, 2.0], [3.0, 4.0]])
        """
    def scalar(self) -> Expression:
        r"""
        Extract the scalar value from a rank-0 (scalar) tensor.

        Returns
        -------
        Expression
            The scalar expression contained in this tensor

        Raises
        ------
        RuntimeError
            If the tensor is not a scalar

        Examples
        --------
        >>> from symbolica.community.spenso import Tensor, TensorName, Representation
        >>> rep = Representation.euc(2)
        >>> p = TensorName.vector("p")
        >>> structure = (p(rep("mu")) * p(rep("mu"))).with_name(TensorName("p2"))
        >>> scalar_tensor = Tensor.dense(structure, [1.0])
        >>> value = scalar_tensor.scalar()
        """
    def index(
        self, *indices: typing.Any, cook_indices: builtins.bool = ...
    ) -> TensorNetwork:
        r"""
        Reference this tensor with new abstract indices and return a lazy network.
        """
    def __call__(
        self, *indices: typing.Any, cook_indices: builtins.bool = ...
    ) -> TensorNetwork:
        r"""
        Reference this tensor with new abstract indices and return a lazy network.
        """
    def __neg__(self) -> TensorNetwork: ...
    def __add__(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork: ...
    def __radd__(
        self,
        lhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork: ...
    def __sub__(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork: ...
    def __rsub__(
        self,
        lhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork: ...
    def __mul__(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork: ...
    def __rmul__(
        self,
        lhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork: ...
    def __truediv__(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork: ...
    def __rtruediv__(
        self,
        lhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork: ...
    def outer(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork: ...
    def contract(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
        *,
        left: builtins.int,
        right: builtins.int,
    ) -> TensorNetwork: ...
    def compose(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
        *,
        left: tuple[builtins.int, builtins.int],
        right: tuple[builtins.int, builtins.int],
    ) -> TensorNetwork: ...
    def dot(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork: ...
    def trace(
        self, *, channel: typing.Optional[tuple[builtins.int, builtins.int]] = None
    ) -> TensorNetwork: ...
    def __iter__(self) -> typing.Iterator[typing.Any]:
        r"""
        Iterator
        """

@typing.final
class TensorEvaluator:
    r"""
    An optimized evaluator for symbolic tensor expressions.

    An optimized evaluator for symbolic tensor expressions.

    This class provides efficient numerical evaluation of symbolic tensor expressions
    after optimization. It supports both real and complex-valued evaluations.

    Create instances using the `Tensor.evaluator()` method rather than directly.

    Examples
    --------
    >>> evaluator = my_tensor.evaluator(constants={}, funs={}, params=[x, y])
    >>> results = evaluator.evaluate([[1.0, 2.0], [3.0, 4.0]])
    """
    def evaluate(
        self, inputs: typing.Sequence[typing.Sequence[builtins.float]]
    ) -> builtins.list[Tensor]:
        r"""
        Evaluate the tensor expression for multiple real-valued parameter inputs.

        Parameters
        ----------
        inputs : list of list of float
            List of parameter value lists, where each inner list contains
            numerical values for all parameters in the same order as specified
            when creating the evaluator

        Returns
        -------
        list of Tensor
            List of evaluated tensors, one for each input parameter set

        Raises
        ------
        ValueError
            If the evaluator contains complex coefficients

        Examples
        --------
        >>> results = evaluator.evaluate([[1.0, 2.0], [3.0, 4.0]])
        """
    def evaluate_complex(
        self, inputs: typing.Sequence[typing.Sequence[builtins.complex]]
    ) -> builtins.list[Tensor]:
        r"""
        Evaluate the expression for multiple inputs and return the results.
        """
    def compile(
        self,
        function_name: builtins.str,
        filename: builtins.str,
        library_name: builtins.str,
        inline_asm: builtins.str = ...,
        optimization_level: builtins.int = ...,
        compiler_path: typing.Optional[builtins.str] = None,
        custom_header: typing.Optional[builtins.str] = None,
    ) -> CompiledTensorEvaluator:
        r"""
        Compile the evaluator to a shared library using C++ for maximum performance.

        Compile the evaluator to a shared library using C++ for maximum performance.

        Generates optimized C++ code with optional inline assembly and compiles it
        into a shared library that can be loaded for extremely fast evaluation.

        Parameters
        ----------
        function_name : str
            Name for the generated C++ function
        filename : str
            Path for the generated C++ source file
        library_name : str
            Name for the compiled shared library
        inline_asm : str, optional
            Type of inline assembly optimization ("default", "x64", "aarch64", "none")
        optimization_level : int, optional
            Compiler optimization level 0-3 (default: 3)
        compiler_path : str, optional
            Path to specific C++ compiler (default: system default)
        custom_header : str, optional
            Additional C++ header code to include

        Returns
        -------
        CompiledTensorEvaluator
            A compiled evaluator for maximum performance evaluation

        Examples
        --------
        >>> compiled = evaluator.compile(
        ...     function_name="fast_eval",
        ...     filename="tensor_eval.cpp",
        ...     library_name="tensor_lib",
        ...     optimization_level=3,
        ... )
        >>> results = compiled.evaluate_complex([[1.0, 2.0], [3.0, 4.0]])
        """

@typing.final
class TensorExpression(Expression):
    r"""
    A Symbolica expression with an ordered external tensor interface.
    """
    @property
    def rank(self) -> builtins.int: ...
    @property
    def is_scalar(self) -> builtins.bool: ...
    @property
    def interface(self) -> tuple: ...
    @property
    def name(self) -> typing.Optional[TensorName]:
        r"""
        The optional identity used when this expression describes stored data.
        """
    def with_name(
        self, name: TensorName | builtins.str | Expression | TensorExpression
    ) -> TensorExpression:
        r"""
        Return a named descriptor without changing the underlying expression.
        """
    def __len__(self) -> builtins.int: ...
    def to_expression(self) -> Expression: ...
    def reinfer(self) -> TensorExpression: ...
    def expand(
        self,
        var: typing.Optional[Expression | int | str | float | builtins.complex] = None,
        via_poly: typing.Optional[builtins.bool] = None,
    ) -> TensorExpression:
        r"""
        Expand scalar algebra while preserving and validating the tensor interface.
        """
    def simplify_gamma(
        self, settings: typing.Optional[GammaSimplifySettings] = None
    ) -> TensorExpression:
        r"""
        Apply Idenso's gamma-algebra simplifier and re-infer the tensor interface.
        """
    def collect_gamma_chains(self) -> TensorExpression: ...
    def simplify_gamma0(self) -> TensorExpression: ...
    def simplify_gamma_conjugate(self) -> TensorExpression: ...
    def simplify_epsilon(self) -> TensorExpression: ...
    def simplify_metrics(self) -> TensorExpression: ...
    def simplify_color(
        self, settings: typing.Optional[ColorSimplifySettings] = None
    ) -> TensorExpression: ...
    def collect_color(self) -> TensorExpression: ...
    def collect_color_constants(self) -> TensorExpression: ...
    def to_color_casimir(
        self,
        *,
        fundamental: Representation,
        adjoint: Representation,
        settings: typing.Optional[ColorCasimirSettings] = None,
    ) -> TensorExpression: ...
    def to_cof_dimension_invariants(self) -> TensorExpression: ...
    def wrap_color(self, symbol: Expression) -> TensorExpression: ...
    def expand_mink(self) -> builtins.list[tuple[Expression, Expression]]: ...
    def expand_bis(self) -> builtins.list[tuple[Expression, Expression]]: ...
    def expand_mink_bis(self) -> builtins.list[tuple[Expression, Expression]]: ...
    def expand_metrics(self) -> builtins.list[tuple[Expression, Expression]]: ...
    def expand_color(self) -> builtins.list[tuple[Expression, Expression]]: ...
    def expand_in_patterns(
        self, patterns: typing.Sequence[Expression]
    ) -> builtins.list[tuple[Expression, Expression]]: ...
    def wrap_indices(self, header: Expression) -> TensorExpression: ...
    def cook_indices(
        self, settings: typing.Optional[CookSettings] = None
    ) -> TensorExpression: ...
    def cook_function(
        self, settings: typing.Optional[CookSettings] = None
    ) -> Expression: ...
    def wrap_dummies(self, header: Expression) -> TensorExpression: ...
    def list_dangling(self) -> builtins.list[Expression]: ...
    def canonize(self) -> TensorExpression: ...
    def alias_subtensors(
        self, tensor_name: builtins.str
    ) -> tuple[Expression, builtins.list[tuple[Expression, Expression]]]: ...
    def spenso_conjugate(self) -> TensorExpression: ...
    def conjugate_transpose(
        self, representation: Representation
    ) -> TensorExpression: ...
    def dirac_adjoint(self) -> TensorExpression: ...
    def cook(self, settings: typing.Optional[CookSettings] = None) -> Expression:
        r"""
        Encode this expression using Idenso's reversible cooking format.
        """
    def uncook(
        self, settings: typing.Optional[CookSettings] = None
    ) -> TensorExpression: ...
    def schoonschip(
        self, settings: typing.Optional[SchoonschipSettings] = None
    ) -> TensorExpression: ...
    def schoonschip_net(
        self,
        settings: typing.Optional[SchoonschipSettings] = None,
        *,
        expand_contracted_sums: builtins.bool = ...,
    ) -> TensorExpression: ...
    def to_dots(self) -> TensorExpression: ...
    def normalize_dots(self) -> TensorExpression: ...
    def expand_dots(self) -> TensorExpression: ...
    def metric_shorthand_to_dot(self) -> TensorExpression: ...
    def undo_all(self) -> TensorExpression: ...
    def undo_schoonschip(self) -> TensorExpression: ...
    def undo_dots(self) -> TensorExpression: ...
    def undo_chain(self) -> TensorExpression: ...
    def undo_trace(self) -> TensorExpression: ...
    def collect_chains(self, representation: Representation) -> TensorExpression: ...
    def chainify(self, representation: Representation) -> TensorExpression: ...
    def normalize_chains(self) -> TensorExpression: ...
    def undo_single_length(self) -> TensorExpression: ...
    def to_network(
        self, library: typing.Optional[TensorLibrary] = None
    ) -> TensorNetwork:
        r"""
        Materialize unresolved ports and parse this expression as a tensor network.
        """
    def index(
        self, *indices: typing.Any, cook_indices: builtins.bool = ...
    ) -> TensorExpression: ...
    def __call__(
        self, *indices: typing.Any, cook_indices: builtins.bool = ...
    ) -> TensorExpression: ...
    def __neg__(self) -> TensorExpression: ...
    def __add__(self, rhs: typing.Any) -> TensorExpression | TensorNetwork: ...
    def __radd__(self, lhs: typing.Any) -> TensorExpression | TensorNetwork: ...
    def __sub__(self, rhs: typing.Any) -> TensorExpression | TensorNetwork: ...
    def __rsub__(self, lhs: typing.Any) -> TensorExpression | TensorNetwork: ...
    def __mul__(self, rhs: typing.Any) -> TensorExpression | TensorNetwork: ...
    def __rmul__(self, lhs: typing.Any) -> TensorExpression | TensorNetwork: ...
    def __truediv__(self, rhs: typing.Any) -> TensorExpression | TensorNetwork: ...
    def __rtruediv__(self, lhs: typing.Any) -> TensorExpression | TensorNetwork: ...
    def outer(self, rhs: typing.Any) -> TensorExpression | TensorNetwork: ...
    def contract(
        self, rhs: typing.Any, *, left: builtins.int, right: builtins.int
    ) -> TensorExpression | TensorNetwork: ...
    def compose(
        self,
        rhs: typing.Any,
        *,
        left: tuple[builtins.int, builtins.int],
        right: tuple[builtins.int, builtins.int],
    ) -> TensorExpression | TensorNetwork: ...
    def trace(
        self, *, channel: typing.Optional[tuple[builtins.int, builtins.int]] = None
    ) -> TensorExpression: ...
    def format_tensor(self, show_dimensions: builtins.bool = ...) -> builtins.str: ...
    def to_typst(self, show_dimensions: builtins.bool = ...) -> builtins.str: ...
    def formatted(self, show_dimensions: builtins.bool = ...) -> FormattedOutput: ...
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def _repr_pretty_(self, pretty: typing.Any, cycle: builtins.bool) -> None: ...
    def _repr_html_(self) -> typing.Optional[builtins.str]: ...
    def _repr_latex_(self) -> builtins.str: ...
    @typing.overload
    def __getitem__(self, item: builtins.int) -> builtins.list[builtins.int]:
        r"""
        Convert a logical row-major flat index to tensor coordinates.
        """
    @typing.overload
    def __getitem__(self, item: typing.Sequence[builtins.int]) -> builtins.int:
        r"""
        Convert tensor coordinates to a logical row-major flat index.
        """
    @typing.overload
    def __getitem__(
        self, item: builtins.slice
    ) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Expand a slice of logical row-major flat indices to tensor coordinates.
        """

@typing.final
class TensorFunctionLibrary:
    def __new__(cls) -> TensorFunctionLibrary:
        r"""
        Create a new empty tensor function library.

        Initializes an empty library ready for registering tensor functions.

        Returns
        -------
        TensorFunctionLibrary
            A new empty function library

        Examples
        --------
        >>> from symbolica.community.spenso import TensorFunctionLibrary
        >>> lib = TensorFunctionLibrary()
        """
    def register(self, function: BroadcastFunction, callback: typing.Any) -> None:
        r"""
        Register an elementwise callback for concrete tensor execution.
        """

@typing.final
class TensorLibrary:
    r"""
    A library for registering and managing tensor templates and structures.

    The TensorLibrary provides a centralized registry for tensor definitions that can be
    reused across tensor networks and expressions. It manages tensor structures with their
    associated names and can resolve symbolic references to registered tensors.

    ```python
    from symbolica.community.spenso import Tensor, TensorLibrary, TensorName, Representation

    lib = TensorLibrary()
    rep = Representation.euc(3)
    name = TensorName("my_tensor")
    structure = name(rep, rep)
    tensor = Tensor.dense(structure, [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0])
    lib.register(tensor)
    tensor_ref = lib[name]
    ```
    """
    def __new__(cls) -> TensorLibrary:
        r"""
        Create a new empty tensor library.

        Initializes an empty library ready for registering tensor structures.
        The library automatically manages internal tensor IDs.

        Returns
        -------
        TensorLibrary
            A new empty tensor library

        Examples
        --------
        >>> from symbolica.community.spenso import TensorLibrary
        >>> lib = TensorLibrary()
        """
    @staticmethod
    def construct() -> TensorLibrary:
        r"""
        Create a new empty tensor library (static method).

        Initializes an empty library ready for registering tensor structures.
        The library automatically manages internal tensor IDs.

        Returns
        -------
        TensorLibrary
            A new empty tensor library

        Examples
        --------
        >>> from symbolica.community.spenso import TensorLibrary
        >>> lib = TensorLibrary.construct()
        """
    def register(self, tensor: Tensor) -> None:
        r"""
        Register a tensor in the library.

        Adds a tensor template to the library that can be referenced by name
        in tensor networks and symbolic expressions. The tensor must have a name
        set in its structure.

        Parameters
        ----------
        tensor : Tensor
            A named tensor with a fully unresolved interface, or a named scalar

        Examples
        --------
        >>> from symbolica.community.spenso import Tensor, TensorLibrary, TensorName, Representation
        >>> lib = TensorLibrary()
        >>> rep = Representation.euc(3)
        >>> name = TensorName("my_tensor")
        >>> structure = name(rep, rep)
        >>> tensor = Tensor.dense(structure, [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0])
        >>> lib.register(tensor)
        >>> tensor_ref = lib[name]
        """
    def __getitem__(
        self, key: TensorExpression | TensorName | Expression | builtins.str
    ) -> TensorExpression:
        r"""
        Retrieve a registered tensor structure by name.

        Looks up a previously registered tensor by its name and returns
        a reference structure that can be used to create new tensor instances.

        Parameters
        ----------
        key : TensorExpression, TensorName, Expression, or str
            An exact unresolved tensor signature, or a symbol-only convenience key

        Returns
        -------
        TensorExpression
            An atomic reference with the registered tensor's logical interface

        Raises
        ------
        RuntimeError
            If the tensor name is not found in the library

        Examples
        --------
        >>> exact = lib[TensorName("T")(1, Representation.euc(3))]
        >>> unique_by_name = lib["T"]
        """
    @staticmethod
    def hep_lib() -> TensorLibrary:
        r"""
        Create a library pre-loaded with High Energy Physics tensor definitions.

        Returns a library containing standard HEP tensors such as gamma matrices,
        color generators, metric tensors, and other commonly used structures in
        particle physics calculations. They are floating point tensors with f64 precision.

        Returns
        -------
        TensorLibrary
            A TensorLibrary pre-populated with HEP tensor definitions

        Examples
        --------
        >>> import symbolica
        >>> from symbolica.community.spenso import TensorLibrary, TensorName
        >>> hep_lib = TensorLibrary.hep_lib()
        >>> gamma_structure = hep_lib[symbolica.S("spenso::gamma")]
        """
    @staticmethod
    def hep_lib_atom() -> TensorLibrary:
        r"""
        Create a library pre-loaded with High Energy Physics tensor definitions.

        Returns a library containing standard HEP tensors such as gamma matrices,
        color generators, metric tensors, and other commonly used structures in
        particle physics calculations. They are tensors with atom numeric entries.

        Returns
        -------
        TensorLibrary
            A TensorLibrary pre-populated with HEP tensor definitions

        Examples
        --------
        >>> import symbolica
        >>> from symbolica.community.spenso import TensorLibrary, TensorName
        >>> hep_lib = TensorLibrary.hep_lib_atom()
        >>> gamma_structure = hep_lib[symbolica.S("spenso::gamma")]
        """

@typing.final
class TensorName:
    r"""
    A symbolic name for tensor expressions.

    TensorName represents named tensor functions that can be called with scalar arguments, slots,
    and representations to create tensor expressions. Names can have various mathematical properties like symmetry,
    antisymmetry, and custom normalization or printing behavior.

    Examples
    --------
    >>> from symbolica.community.spenso import TensorName, Slot, Representation
    >>> T = TensorName("T")
    >>> symmetric_T = TensorName("S", is_symmetric=True)
    >>> antisymmetric_T = TensorName("A", is_antisymmetric=True)
    >>> rep = Representation.cof(3)
    >>> mu = rep('mu')
    >>> nu = rep('nu')
    >>> tensor_expression = T(mu, nu)
    """
    def __new__(
        cls,
        name: builtins.str,
        *,
        rank: typing.Optional[builtins.int] = None,
        is_symmetric: typing.Optional[builtins.bool] = None,
        is_antisymmetric: typing.Optional[builtins.bool] = None,
        is_cyclesymmetric: typing.Optional[builtins.bool] = None,
        is_linear: typing.Optional[builtins.bool] = None,
        is_flat: typing.Optional[builtins.bool] = None,
        is_scalar: typing.Optional[builtins.bool] = None,
        is_real: typing.Optional[builtins.bool] = None,
        is_integer: typing.Optional[builtins.bool] = None,
        is_positive: typing.Optional[builtins.bool] = None,
        tags: typing.Optional[typing.Sequence[builtins.str]] = None,
        aliases: typing.Optional[typing.Sequence[builtins.str]] = None,
        normalization: typing.Optional[Transformer] = None,
        print: typing.Optional[typing.Any] = None,
        derivative: typing.Optional[typing.Any] = None,
        series: typing.Optional[typing.Any] = None,
        eval: typing.Optional[typing.Any] = None,
        data: typing.Optional[
            Expression
            | int
            | str
            | float
            | builtins.complex
            | str
            | dict
            | list
            | bytes
        ] = None,
    ) -> TensorName:
        r"""
        Create a new tensor name with optional mathematical properties.

        Parameters
        ----------
        name : str
            The string name for the tensor function
        is_symmetric : bool, optional
            If True, tensor is symmetric under index permutation
        is_antisymmetric : bool, optional
            If True, tensor is antisymmetric under index permutation
        is_cyclesymmetric : bool, optional
            If True, tensor is symmetric under cyclic permutations
        is_linear : bool, optional
            If True, tensor is linear in its arguments
        rank : int, optional
            The declared rank. Only rank one has a dedicated construction invariant.
        tags : list[str], optional
            Extra Symbolica tags. The Spenso tensor tag is always included.
        normalization, print, derivative, series, eval, data : optional
            Symbolica symbol callbacks and metadata.

        Returns
        -------
        TensorName
            A new TensorName with the specified properties

        Examples
        --------
        >>> from symbolica.community.spenso import TensorName
        >>> T = TensorName("T")
        >>> g = TensorName("g", is_symmetric=True)
        >>> F = TensorName("F", is_antisymmetric=True)
        >>> D = TensorName("D", is_linear=True)
        """
    @staticmethod
    def vector(
        name: builtins.str,
        *,
        is_symmetric: typing.Optional[builtins.bool] = None,
        is_antisymmetric: typing.Optional[builtins.bool] = None,
        is_cyclesymmetric: typing.Optional[builtins.bool] = None,
        is_linear: typing.Optional[builtins.bool] = None,
        is_flat: typing.Optional[builtins.bool] = None,
        is_scalar: typing.Optional[builtins.bool] = None,
        is_real: typing.Optional[builtins.bool] = None,
        is_integer: typing.Optional[builtins.bool] = None,
        is_positive: typing.Optional[builtins.bool] = None,
        tags: typing.Optional[typing.Sequence[builtins.str]] = None,
        aliases: typing.Optional[typing.Sequence[builtins.str]] = None,
        normalization: typing.Optional[Transformer] = None,
        print: typing.Optional[typing.Any] = None,
        derivative: typing.Optional[typing.Any] = None,
        series: typing.Optional[typing.Any] = None,
        eval: typing.Optional[typing.Any] = None,
        data: typing.Optional[
            Expression
            | int
            | str
            | float
            | builtins.complex
            | str
            | dict
            | list
            | bytes
        ] = None,
    ) -> TensorName:
        r"""
        Create a rank-one tensor name.
        """
    def __repr__(self) -> builtins.str: ...
    def __str__(self) -> builtins.str: ...
    def to_expression(self) -> Expression:
        r"""
        Convert the tensor name to a symbolic expression.

        Returns
        -------
        Expression
            A symbolic Expression representing this tensor name

        Examples
        --------
        >>> T = TensorName("T")
        >>> expr = T.to_expression()
        """
    def has_tag(self, tag: builtins.str) -> builtins.bool:
        r"""
        Check whether this tensor name carries `tag`.
        """
    def get_tags(self) -> builtins.list[builtins.str]:
        r"""
        Return all Symbolica tags carried by this tensor name.
        """
    @staticmethod
    def g() -> TensorName:
        r"""
        Predefined metric tensor name.
        """
    @staticmethod
    def flat() -> TensorName:
        r"""
        Predefined musical isomorphism tensor name. This enables dualizing self dual indices.
        """
    @staticmethod
    def gamma() -> TensorName:
        r"""
        Predefined gamma matrix name.
        """
    @staticmethod
    def gamma5() -> TensorName:
        r"""
        Predefined gamma5 matrix name.
        """
    @staticmethod
    def projm() -> TensorName:
        r"""
        Predefined left chiral projector name.
        """
    @staticmethod
    def projp() -> TensorName:
        r"""
        Predefined right chiral projector name.
        """
    @staticmethod
    def sigma() -> TensorName:
        r"""
        Predefined sigma matrix name.
        """
    @staticmethod
    def f() -> TensorName:
        r"""
        Predefined color structure constant name.
        """
    @staticmethod
    def t() -> TensorName:
        r"""
        Predefined color generator name.
        """
    def __call__(
        self,
        *args: Slot
        | Representation
        | Expression
        | int
        | str
        | float
        | builtins.complex,
    ) -> TensorExpression:
        r"""
        Call the tensor name with arguments to create a tensor expression.

        Accepts scalar key expressions followed by any mix of slots and representations.

        Parameters
        ----------
        *args : Expression, Slot, or Representation
            Scalar key expressions followed by structural ports

        Returns
        -------
        TensorExpression
            A structured expression with explicit and/or unresolved ports

        Examples
        --------
        >>> from symbolica.community.spenso import TensorName, Slot, Representation
        >>> import symbolica as sp
        >>> T = TensorName("T")
        >>> rep = Representation.euc(3)
        >>> mu = rep("mu")
        >>> tensor = T(mu, rep)
        """

@typing.final
class TensorNetwork:
    r"""
    A tensor network representing computational graphs of tensor operations.

    A tensor network is a graph-based representation of tensor computations where
    nodes represent tensors and operations, edges represent tensor contractions and
    data flow, and the network can be optimized and executed to compute results.

    Tensor networks are particularly useful for symbolic manipulation of complex
    tensor expressions, optimization of tensor contraction orders, efficient
    evaluation of large tensor computations, and physics calculations involving
    many-body systems.

    Examples
    --------
    >>> from symbolica.community.spenso import TensorNetwork, Tensor, TensorName, Representation
    >>> rep = Representation.euc(2)
    >>> T = TensorName("T")
    >>> tensor = Tensor.dense(T(rep("mu"), rep("nu")), [1.0, 0.0, 0.0, 1.0])
    >>> network = TensorNetwork(tensor)
    >>> network.execute()
    >>> result = network.result_tensor()
    """
    def __new__(
        cls, expr: typing.Any, library: typing.Optional[TensorLibrary] = None
    ) -> TensorNetwork:
        r"""
        Create a tensor network by parsing an arithmetic expression.

        Parses symbolic expressions containing tensor operations and converts them
        into an optimizable computational graph representation.

        Parameters
        ----------
        expr : ArithmeticStructure
            The arithmetic expression or tensor structure to parse
        library : TensorLibrary, optional
            Optional tensor library for resolving named tensor references

        Returns
        -------
        TensorNetwork
            A new TensorNetwork representing the parsed expression
        """
    @staticmethod
    def one() -> TensorNetwork:
        r"""
        Create a tensor network representing the scalar value 1.

        Returns
        -------
        TensorNetwork
            A TensorNetwork containing only the scalar 1

        Examples
        --------
        >>> from symbolica.community.spenso import TensorNetwork
        >>> one_net = TensorNetwork.one()
        >>> result = one_net.result_scalar()
        """
    @staticmethod
    def bracket() -> Expression: ...
    @staticmethod
    def broadcast(str: builtins.str) -> Expression: ...
    @staticmethod
    def zero() -> TensorNetwork:
        r"""
        Create a tensor network representing the scalar value 0.

        Returns
        -------
        TensorNetwork
            A TensorNetwork containing only the scalar 0

        Examples
        --------
        >>> from symbolica.community.spenso import TensorNetwork
        >>> zero_net = TensorNetwork.zero()
        >>> result = zero_net.result_scalar()
        """
    def replace(
        self,
        pattern: Expression | int | str | float | builtins.complex,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | HeldExpression
        | typing.Callable[[dict[Expression, Expression]], Expression]
        | int
        | float
        | complex
        | decimal.Decimal,
        _cond: typing.Optional[PatternRestriction | Condition] = None,
        non_greedy_wildcards: typing.Optional[typing.Sequence[Expression]] = None,
        level_range: typing.Optional[
            tuple[builtins.int, typing.Optional[builtins.int]]
        ] = None,
        level_is_tree_depth: typing.Optional[builtins.bool] = None,
        allow_new_wildcards_on_rhs: typing.Optional[builtins.bool] = None,
        rhs_cache_size: typing.Optional[builtins.int] = None,
        repeat: typing.Optional[builtins.bool] = None,
    ) -> TensorNetwork:
        r"""
        Replace patterns in the tensor network using symbolic pattern matching.

        Applies pattern-based transformations to the network structure, allowing for
        symbolic simplifications, substitutions, and algebraic manipulations.

        Parameters
        ----------
        pattern : Expression
            The symbolic pattern to match against
        rhs : Expression
            The replacement expression or pattern
        non_greedy_wildcards : list of Expression, optional
            List of wildcard symbols to match non-greedily
        level_range : tuple of int, optional
            Tuple specifying depth range for pattern matching
        level_is_tree_depth : bool, optional
            Whether level refers to tree depth or expression depth
        allow_new_wildcards_on_rhs : bool, optional
            Allow new wildcards in replacement pattern
        rhs_cache_size : int, optional
            Size of cache for replacement pattern compilation
        repeat : bool, optional
            Whether to repeatedly apply the replacement until no more matches

        Returns
        -------
        TensorNetwork
            A new TensorNetwork with the replacements applied
        """
    def evaluate(
        self,
        constants: typing.Mapping[Expression, builtins.float],
        functions: typing.Mapping[Expression, typing.Any],
    ) -> TensorNetwork:
        r"""
        Evaluate symbolic expressions in the network with numerical values.

        Substitutes symbolic constants and functions with numerical values,
        converting symbolic parts of the network to concrete numerical tensors.

        Parameters
        ----------
        constants : dict
            Dict mapping symbolic expressions to their numerical values
        functions : dict
            Dict mapping function symbols to Python callable objects

        Returns
        -------
        TensorNetwork
            A new TensorNetwork with symbolic expressions evaluated
        """
    def execute(
        self,
        library: typing.Optional[TensorLibrary] = None,
        function_library: typing.Optional[TensorFunctionLibrary] = None,
        n_steps: typing.Optional[builtins.int] = None,
        mode: ExecutionMode = ...,
    ) -> None:
        r"""
        Execute the tensor network to perform tensor contractions and simplifications.

        Processes the computational graph by executing tensor operations such as
        contractions, additions, and multiplications. The execution can be controlled
        by mode and step limits.

        Parameters
        ----------
        library : TensorLibrary, optional
            Optional tensor library for resolving tensor operations
        n_steps : int, optional
            Maximum number of execution steps (None for complete execution)
        mode : ExecutionMode, optional
            Execution strategy (ExecutionMode.All, ExecutionMode.Scalar, or ExecutionMode.Single)

        Examples
        --------
        >>> from symbolica.community.spenso import TensorNetwork, ExecutionMode, TensorLibrary
        >>> network = TensorNetwork(some_expression)
        >>> network.execute()
        >>> network.execute(n_steps=5)
        >>> network.execute(mode=ExecutionMode.Scalar)
        >>> lib = TensorLibrary.hep_lib()
        >>> network.execute(library=lib)
        """
    def result_tensor(self, library: typing.Optional[TensorLibrary] = None) -> Tensor:
        r"""
        Extract the final tensor result from the executed network.

        After network execution, retrieves the computed tensor result. The network
        should be executed before calling this method.

        Parameters
        ----------
        library : TensorLibrary, optional
            Optional tensor library for resolving tensor structures

        Returns
        -------
        Tensor
            The computed tensor result

        Raises
        ------
        RuntimeError
            If the network execution resulted in an error

        Examples
        --------
        >>> from symbolica.community.spenso import TensorNetwork, TensorLibrary
        >>> network = TensorNetwork(tensor_expression)
        >>> network.execute()
        >>> result = network.result_tensor()
        >>> lib = TensorLibrary.hep_lib()
        >>> result_with_lib = network.result_tensor(library=lib)
        """
    def result_scalar(self) -> Expression:
        r"""
        Extract the final scalar result from the executed network.

        For networks that evaluate to scalar expressions, retrieves the computed
        scalar value. The network should be executed before calling this method.

        Returns
        -------
        Expression
            The computed scalar expression

        Raises
        ------
        RuntimeError
            If the network execution resulted in an error

        Examples
        --------
        >>> from symbolica.community.spenso import TensorNetwork
        >>> network = TensorNetwork(scalar_expression)
        >>> network.execute()
        >>> scalar_result = network.result_scalar()
        """
    def __str__(self) -> builtins.str:
        r"""
        Return a string representation of the network structure.

        Generates a DOT format representation of the computational graph that can be
        visualized using graphviz or similar tools.
        """
    def format_tensor(self, show_dimensions: builtins.bool = ...) -> builtins.str:
        r"""
        Format the exact semantic structure using compact Spenso notation.
        """
    def to_typst(self, show_dimensions: builtins.bool = ...) -> builtins.str:
        r"""
        Format the exact semantic structure as Typst math source.
        """
    def formatted(self, show_dimensions: builtins.bool = ...) -> FormattedOutput:
        r"""
        Build Symbolica's rich display wrapper for the semantic structure.
        """
    def structure(self) -> TensorExpression:
        r"""
        Return the exact structured expression represented by this network.
        """
    def index(
        self, *indices: typing.Any, cook_indices: builtins.bool = ...
    ) -> TensorNetwork: ...
    def __call__(
        self, *indices: typing.Any, cook_indices: builtins.bool = ...
    ) -> TensorNetwork: ...
    def __neg__(self) -> TensorNetwork: ...
    def __add__(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork:
        r"""
        Add two tensor networks element-wise.

        Parameters
        ----------
        rhs : TensorNetwork
            The tensor network to add (right-hand side)

        Returns
        -------
        TensorNetwork
            A new TensorNetwork representing the sum

        Examples
        --------
        >>> net1 = TensorNetwork(expr1)
        >>> net2 = TensorNetwork(expr2)
        >>> sum_net = net1 + net2
        """
    def __radd__(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork:
        r"""
        Add two tensor networks element-wise (right-hand addition).
        """
    def __sub__(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork:
        r"""
        Subtract one tensor network from another element-wise.

        Parameters
        ----------
        rhs : TensorNetwork
            The tensor network to subtract (right-hand side)

        Returns
        -------
        TensorNetwork
            A new TensorNetwork representing the difference

        Examples
        --------
        >>> net1 = TensorNetwork(expr1)
        >>> net2 = TensorNetwork(expr2)
        >>> diff_net = net1 - net2
        """
    def __rsub__(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork:
        r"""
        Subtract one tensor network from another (right-hand subtraction).
        """
    def __mul__(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork:
        r"""
        Multiply two tensor networks.

        Parameters
        ----------
        rhs : TensorNetwork
            The tensor network to multiply with (right-hand side)

        Returns
        -------
        TensorNetwork
            A new TensorNetwork representing the product

        Examples
        --------
        >>> net1 = TensorNetwork(expr1)
        >>> net2 = TensorNetwork(expr2)
        >>> product_net = net1 * net2
        """
    def __rmul__(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork:
        r"""
        Multiply two tensor networks (right-hand multiplication).
        """
    def __truediv__(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork: ...
    def __rtruediv__(
        self,
        lhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork: ...
    def outer(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork:
        r"""
        Form an outer tensor product without contracting compatible ports.
        """
    def contract(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
        *,
        left: builtins.int,
        right: builtins.int,
    ) -> TensorNetwork:
        r"""
        Contract one selected pair of public interface positions.
        """
    def compose(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
        *,
        left: tuple[builtins.int, builtins.int],
        right: tuple[builtins.int, builtins.int],
    ) -> TensorNetwork:
        r"""
        Compose two explicitly selected matrix channels.
        """
    def dot(
        self,
        rhs: Expression
        | int
        | str
        | float
        | builtins.complex
        | TensorExpression
        | TensorNetwork
        | Tensor,
    ) -> TensorNetwork:
        r"""
        Contract two rank-one operands into the canonical dot form.
        """
    def trace(
        self, *, channel: typing.Optional[tuple[builtins.int, builtins.int]] = None
    ) -> TensorNetwork:
        r"""
        Close a selected or uniquely inferred propagation channel.
        """

@typing.final
class _AutoIndex:
    r"""
    The local placeholder used to leave a tensor port unresolved.
    """

    ...

@typing.final
class ExecutionMode(enum.Enum):
    r"""
    Execution modes for tensor network evaluation.

    Controls how the tensor network execution engine processes the computational graph.

    Variants
    --------
    Single : Execute one contraction at a time, useful for debugging
    Scalar : Only contract scalar operations, leaving tensor structure intact
    All : Execute all possible contractions for complete evaluation
    """

    Single = ...
    Scalar = ...
    All = ...

@typing.final
class SymbolicParallelism(enum.Enum):
    r"""
    Policy for Rayon operations that manipulate Symbolica expressions.
    """

    Auto = ...
    r"""
    Permit Rayon when licensed and use workload heuristics where available.
    """
    Serial = ...
    r"""
    Keep symbolic operations on the calling thread.
    """
    Parallel = ...
    r"""
    Force Rayon without `Auto`'s Symbolica license safety check.
    """

def as_tensor(expression: typing.Any) -> TensorExpression:
    r"""
    Restore tensor-aware dispatch after a base Symbolica transformation.
    """

def chain(
    start_slot: Slot, end_slot: Slot, *factors: typing.Any
) -> TensorExpression | TensorNetwork:
    r"""
    Build an explicitly-ended ordered tensor chain.
    """

def dot(left: typing.Any, right: typing.Any) -> TensorExpression | TensorNetwork:
    r"""
    Contract two rank-one tensors into the canonical dot form.
    """

def format_tensor(
    expression: Expression, show_dimensions: builtins.bool = ...
) -> builtins.str:
    r"""
    Format a tensor expression using compact Spenso notation.
    """

def formatted(
    expression: Expression, show_dimensions: builtins.bool = ...
) -> FormattedOutput:
    r"""
    Build Symbolica's rich display wrapper for a tensor expression.
    """

def set_symbolica_rayon_enabled(policy: SymbolicParallelism) -> builtins.bool:
    r"""
    Configure whether Spenso may use Rayon for Symbolica operations.

    `Auto` checks the Symbolica license once during this call. When licensed,
    operations may use Rayon and apply workload heuristics where available;
    when unlicensed, symbolic operations remain serial. The returned boolean
    reports whether the resolved policy permits Rayon, not whether every
    operation will use it.
    """

def to_typst(
    expression: Expression, show_dimensions: builtins.bool = ...
) -> builtins.str:
    r"""
    Format a tensor expression as Typst math source.
    """

def trace(
    representation: Representation, *factors: typing.Any
) -> TensorExpression | TensorNetwork:
    r"""
    Close an ordered factor sequence into a canonical cyclic trace.
    """
