"""Static checks that FeynKit's public API comes directly from PyO3."""

import ast
from pathlib import Path

ROOT = Path(__file__).parents[1]
PACKAGE = ROOT / "python" / "symbolica" / "community" / "feynkit"
INITIALIZER = PACKAGE / "__init__.py"
STUB = PACKAGE / "__init__.pyi"
STUB_GENERATOR = ROOT / "src" / "bin" / "stub_gen.rs"
REMOVED_FACADE_FILES = (
    PACKAGE / "_workflows.py",
    ROOT / "stubs" / "feynkit_facade.pyi.inc",
)


def test_runtime_package_only_initializes_the_native_module():
    """No Python workflow layer may sit between users and the PyO3 exports."""

    assert all(not path.exists() for path in REMOVED_FACADE_FILES)

    tree = ast.parse(INITIALIZER.read_text())
    imports = [node for node in tree.body if isinstance(node, ast.ImportFrom)]
    assert len(imports) == 1
    assert imports[0].level == 2
    assert imports[0].module == "feynkit_native"
    assert [alias.name for alias in imports[0].names] == ["*"]

    assert any(
        isinstance(node, ast.Expr)
        and isinstance(node.value, ast.Call)
        and isinstance(node.value.func, ast.Name)
        and node.value.func.id == "initialize_module"
        for node in tree.body
    )
    assert any(
        isinstance(node, ast.Delete)
        and any(
            isinstance(target, ast.Name) and target.id == "initialize_module"
            for target in node.targets
        )
        for node in tree.body
    )


def test_stub_is_entirely_generated_from_the_native_module():
    """The checked-in type surface has no handwritten facade declarations."""

    stub = STUB.read_text()
    assert stub.startswith("# This file is automatically generated by pyo3_stub_gen\n")
    assert "Host-maintained conveniences" not in stub
    assert "ParticleLike: typing.TypeAlias" not in stub
    assert "LoopOrder: typing.TypeAlias" not in stub


def test_stub_generator_writes_only_feynkit_py_output():
    """Both regeneration modes source FeynKit declarations from its Rust crate."""

    generator = STUB_GENERATOR.read_text()
    assert "feynkit_py::stub_info()?" in generator
    assert "module.to_string()" in generator
    assert "fs::write(path, source)?" in generator
    assert 'argument == "--feynkit-only"' in generator
    assert "include_str!" not in generator
    assert "push_str" not in generator
    assert "feynkit_facade" not in generator
