# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

from symbolica.core import Expression

def add_two(atom: Expression) -> Expression:
    r"""
    Add two to an atom.
    """
