# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import enum
import typing
from symbolica.community.spenso import Representation
from symbolica.core import Expression

class CanonicalizationError(builtins.ValueError): ...

@typing.final
class ColorCasimirSettings:
    r"""
    Immutable configuration for rewriting color invariants into a Casimir basis.
    """
    @property
    def rewrite_fundamental_dimension(self) -> builtins.bool: ...
    @property
    def substitute_fundamental_index(self) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        rewrite_fundamental_dimension: builtins.bool = ...,
        substitute_fundamental_index: builtins.bool = ...,
    ) -> ColorCasimirSettings: ...

@typing.final
class ColorSimplifySettings:
    r"""
    Immutable configuration for color simplification.
    """
    @property
    def evaluate_traces(self) -> builtins.bool: ...
    @property
    def expand_cross_chain_fierz(self) -> builtins.bool: ...
    @property
    def substitute_cof_dimension_invariants(self) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        evaluate_traces: builtins.bool = ...,
        expand_cross_chain_fierz: builtins.bool = ...,
        substitute_cof_dimension_invariants: builtins.bool = ...,
    ) -> ColorSimplifySettings: ...

@typing.final
class CookSettings:
    r"""
    Immutable configuration for cooking symbolic functions and index payloads.
    """
    @property
    def mode(self) -> CookMode: ...
    @property
    def source_filter(self) -> CookSourceFilter: ...
    @property
    def output_tags(self) -> builtins.list[builtins.str]: ...
    @property
    def preserve_tags(self) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        mode: CookMode = ...,
        source: typing.Optional[CookSourceFilter] = None,
        output_tags: typing.Optional[typing.Sequence[builtins.str]] = None,
        preserve_tags: builtins.bool = ...,
    ) -> CookSettings: ...
    @staticmethod
    def flattened() -> CookSettings: ...
    @staticmethod
    def indices() -> CookSettings: ...
    @staticmethod
    def reversible() -> CookSettings: ...

@typing.final
class CookSourceFilter:
    @staticmethod
    def any_function() -> CookSourceFilter: ...
    @staticmethod
    def function_tags(filter: CookTagFilter) -> CookSourceFilter: ...
    @staticmethod
    def representation_index_payload(
        filter: typing.Optional[CookTagFilter] = None,
    ) -> CookSourceFilter: ...

@typing.final
class CookTagFilter:
    @staticmethod
    def any(tags: typing.Sequence[builtins.str]) -> CookTagFilter: ...
    @staticmethod
    def all(tags: typing.Sequence[builtins.str]) -> CookTagFilter: ...
    @staticmethod
    def matched_output_tags() -> CookTagFilter: ...

class CookingError(builtins.TypeError): ...
class DiracAdjointError(builtins.ValueError): ...
class DotExpansionError(builtins.ValueError): ...
class GammaConjugationError(builtins.ValueError): ...

@typing.final
class GammaSimplifySettings:
    r"""
    Immutable configuration for gamma-chain simplification.
    """
    @property
    def chain_ordering(self) -> GammaChainOrdering: ...
    @property
    def evaluate_traces(self) -> builtins.bool: ...
    @property
    def expand_three_gamma_epsilon(self) -> builtins.bool: ...
    def __new__(
        cls,
        *,
        chain_ordering: GammaChainOrdering = ...,
        evaluate_traces: builtins.bool = ...,
        expand_three_gamma_epsilon: builtins.bool = ...,
    ) -> GammaSimplifySettings: ...
    @staticmethod
    def repeated_pairs() -> GammaSimplifySettings: ...
    @staticmethod
    def canonical() -> GammaSimplifySettings: ...

@typing.final
class SchoonschipSettings:
    r"""
    Immutable configuration for expression and network Schoonschip passes.
    """
    @property
    def depth_limit(self) -> typing.Optional[builtins.int]: ...
    @property
    def mode(self) -> SchoonschipMode: ...
    @property
    def traversal(self) -> typing.Optional[SchoonschipTraversal]: ...
    @property
    def expand_contracted_sums(self) -> builtins.bool: ...
    @property
    def simplify_chain_like_functions(self) -> builtins.bool: ...
    @property
    def schoonschip_rank1_tensors(self) -> builtins.bool: ...
    @property
    def contraction_order(self) -> SchoonschipContractionOrder: ...
    def __new__(
        cls,
        *,
        depth_limit: typing.Optional[builtins.int] = ...,
        mode: SchoonschipMode = ...,
        traversal: SchoonschipTraversal = ...,
        expand_contracted_sums: builtins.bool = ...,
        simplify_chain_like_functions: builtins.bool = ...,
        schoonschip_rank1_tensors: builtins.bool = ...,
        contraction_order: SchoonschipContractionOrder = ...,
    ) -> SchoonschipSettings: ...
    @staticmethod
    def partial() -> SchoonschipSettings: ...
    @staticmethod
    def full() -> SchoonschipSettings: ...
    @staticmethod
    def default_network() -> SchoonschipSettings: ...
    @staticmethod
    def depth_first(
        depth_limit: typing.Optional[builtins.int] = None,
    ) -> SchoonschipSettings: ...
    @staticmethod
    def breadth_first(
        depth_limit: typing.Optional[builtins.int] = None,
    ) -> SchoonschipSettings: ...
    @staticmethod
    def single_pass(
        depth_limit: typing.Optional[builtins.int] = None,
    ) -> SchoonschipSettings: ...

@typing.final
class CookMode(enum.Enum):
    FlattenedSymbol = ...
    ReversibleEncoding = ...

@typing.final
class GammaChainOrdering(enum.Enum):
    r"""
    Controls how open gamma chains are reordered during simplification.
    """

    RepeatedPairs = ...
    Canonical = ...

@typing.final
class SchoonschipContractionOrder(enum.Enum):
    SmallestDegree = ...
    LargestDegree = ...
    MinLargestOperandBytes = ...
    MinProductTerms = ...
    MinProductBytes = ...
    SmallestDegreeMinLargestOperandBytes = ...
    SmallestDegreeMinProductTerms = ...
    SmallestDegreeMinProductBytes = ...

@typing.final
class SchoonschipMode(enum.Enum):
    SinglePass = ...
    Recursive = ...

@typing.final
class SchoonschipTraversal(enum.Enum):
    DepthFirst = ...
    BreadthFirst = ...

def alias_subtensors(
    expression: Expression, tensor_name: builtins.str
) -> tuple[Expression, builtins.list[tuple[Expression, Expression]]]: ...
def canonize(expression: Expression) -> Expression: ...
def chainify(
    expression: Expression, representation: Representation | Expression
) -> Expression: ...
def collect_chains(
    expression: Expression, representation: Representation | Expression
) -> Expression: ...
def collect_color(expression: Expression) -> Expression: ...
def collect_color_constants(expression: Expression) -> Expression: ...
def collect_gamma_chains(expression: Expression) -> Expression: ...
def conjugate_transpose(
    expression: Expression, representation: Representation | Expression
) -> Expression: ...
def cook(
    expression: Expression, settings: typing.Optional[CookSettings] = None
) -> Expression: ...
def cook_function(
    self_: Expression, settings: typing.Optional[CookSettings] = None
) -> Expression:
    r"""
    Convert a single function call into a flattened variable symbol.

    Transforms a function expression with arguments into a single symbolic variable
    whose name encodes both the function name and its arguments. This is the
    atomic version of `cook_indices()`, operating on individual function calls
    rather than complete expressions.

    **Function Cooking Transform:**
    - Simple function: `f(a, b)` → `f_a_b`
    - Nested arguments: `tensor(rep(mu))` → `tensor_rep_mu`
    - Multiple arguments: `gamma(mu, alpha, beta)` → `gamma_mu_alpha_beta`
    - Complex names: `my_function(x, y)` → `my_function_x_y`


    **Constraints:**
    - Input must be a single function call (not sum, product, etc.)
    - Arguments must be cookable (symbols, numbers, simple functions)
    - Cannot cook expressions containing polynomials or complex structures

    # Arguments
    - `self_`: expression representing a single function call to cook

    # Returns
    Expression containing the flattened variable symbol.

    # Raises
    `TypeError` if input is not a cookable function or contains invalid argument types.

    # Examples:
    ```python
    import symbolica as sp
    from symbolica.community.idenso import cook_function

    # Simple function cooking
    f = sp.S('f')
    a, b = sp.S('a','b')

    cooked = cook_function(f(a, b))
    print(cooked)  # Outputs: f_a_b
    ```
    """

def cook_indices(
    self_: Expression, settings: typing.Optional[CookSettings] = None
) -> Expression:
    r"""
    Convert complex nested index structures into flattened symbolic names.

    Transforms hierarchical index expressions within tensor function arguments
    into simplified, flat symbolic representations. This "cooking" process is
    essential for pattern matching, simplification, and computational efficiency
    when dealing with complex tensor expressions.

    **Index Cooking Transformation:**
    - Nested structure: `mink(4, f(g(h(μ))))` → `mink(4, f_g_h_mu)`
    - Function chains: `lorentz(up(mu))` → `lorentz(up_mu)`
    - Complex arguments: `tensor(rep(dim,type(idx)))` → `tensor(rep(dim,type_idx))`

    **Scope:**
    - Only affects indices appearing as function arguments
    - Preserves top-level function structure
    # Arguments
    - `self_`: expression containing complex nested index structures

    # Returns
    Expression with flattened, simplified index names.

    # Examples:
    ```python
    from symbolica.community.spenso import TensorName, Slot, Representation
    import symbolica as sp
    from symbolica.community.idenso import wrap_indices, cook_indices

    T = TensorName("T")
    rep = Representation.euc(3)
    # With slots (creates TensorExpression)
    mu = rep("mu")
    nu = rep("nu")
    x = sp.S("x")
    tensor_with_args = T(x, mu, nu)  # T(x; mu, nu)
    print(tensor_with_args)
    print(
        cook_indices(wrap_indices(tensor_with_args.to_expression(), sp.S("wrap")))
    )
    ```
    """

def dirac_adjoint(self_: Expression) -> Expression: ...
def expand_bis(self_: Expression) -> builtins.list[tuple[Expression, Expression]]:
    r"""
    Expands factorized terms containing Dirac bispinor indices.

    Finds and expands factorized expressions involving bispinor tensors and spinors,
    unfolding multiplicative structures into expanded sums for subsequent simplification.
    Does not expand into explicit components but rather expands nested factorizations.

    **Factorization Expansion:**
    - `ψ(α) * (γ(μ,α,β) + σ(μ,α,β)) → ψ(α)*γ(μ,α,β) + ψ(α)*σ(μ,α,β)`
    - Nested products with bispinor indices get distributed
    - Parenthesized expressions are expanded algebraically
    - Prepares expressions for gamma matrix simplification


    # Arguments
    - `self_`: expression containing factorized terms with bispinor indices

    # Returns
    `(structure, coefficient)` pairs with factorizations unfolded.
    """

def expand_color(self_: Expression) -> builtins.list[tuple[Expression, Expression]]:
    r"""
    Expands factorized terms containing SU(N) color indices.

    Finds and expands factorized expressions involving color tensors and fields,
    unfolding multiplicative structures into expanded sums for subsequent simplification.
    Does not expand into explicit components but rather expands nested factorizations.

    **Factorization Expansion:**
    - `q(a) * (T(b,a,c) + S(b,a,c)) → q(a)*T(b,a,c) + q(a)*S(b,a,c)`
    - Nested products with color indices get distributed
    - Parenthesized expressions are expanded algebraically
    - Prepares expressions for color algebra simplification

    **Applications:**
    - Expanding factorized QCD expressions before simplification
    - Preparing for SU(N) algebra algorithms
    - Unfolding nested products in gauge theory calculations
    - Algebraic manipulation of color structures

    # Arguments
    - `self_`: expression containing factorized terms with color indices

    # Returns
    `(structure, coefficient)` pairs with factorizations unfolded.
    """

def expand_dots(expression: Expression) -> Expression: ...
def expand_in_patterns(
    expression: Expression, patterns: typing.Sequence[Expression]
) -> builtins.list[tuple[Expression, Expression]]:
    r"""
    Selectively expand around the supplied expression patterns.

    Results retain the Rust API's `(structure, coefficient)` factorization.
    """

def expand_metrics(self_: Expression) -> builtins.list[tuple[Expression, Expression]]:
    r"""
    Expands factorized terms containing metric tensors.

    Finds and expands factorized expressions involving metric tensors and related
    geometric objects, unfolding multiplicative structures for subsequent simplification.

    # Arguments
    - `self_`: expression containing factorized metric terms

    # Returns
    `(structure, coefficient)` pairs with metric factorizations unfolded.
    """

def expand_mink(self_: Expression) -> builtins.list[tuple[Expression, Expression]]:
    r"""
    Expands factorized terms containing Minkowski spacetime indices.

    Finds and expands factorized expressions involving Minkowski tensors and vectors,
    unfolding multiplicative structures into expanded sums for subsequent simplification.
    Does not expand into explicit components but rather expands nested factorizations.

    **Factorization Expansion:**
    - `A(μ) * (B(ν) + C(ν)) → A(μ)*B(ν) + A(μ)*C(ν)`
    - Nested products with Minkowski indices get distributed
    - Parenthesized expressions are expanded algebraically
    - Prepares expressions for metric simplification and contractions

    **Applications:**
    - Expanding factorized tensor expressions before simplification
    - Preparing for index contraction algorithms
    - Unfolding nested products in field theory calculations
    - Algebraic manipulation of relativistic expressions

    # Arguments
    - `self_`: expression containing factorized terms with Minkowski indices

    # Returns
    `(structure, coefficient)` pairs with factorizations unfolded.

    # Examples:
    ```python
    import symbolica as sp
    from symbolica.community.idenso import expand_mink

    # Expand factorized vector expression
    p = sp.S('p')
    q = sp.S('q')
    r = sp.S('r')
    mu = sp.S('mu')
    factorized = p(mu) * (q(mu) + r(mu))
    terms = expand_mink(factorized)
    for structure, coefficient in terms:
        print(structure, coefficient)

    # Complex factorization
    A = sp.S('A')
    expr = A * (p(mu) * q(mu) + r(mu))
    terms = expand_mink(expr)
    ```
    """

def expand_mink_bis(self_: Expression) -> builtins.list[tuple[Expression, Expression]]:
    r"""
    Expands factorized terms containing both Minkowski and bispinor indices.

    Combines the functionality of `expand_mink()` and `expand_bis()` to perform
    simultaneous expansion of factorized expressions involving both spacetime
    and spinor indices.

    # Arguments
    - `self_`: expression containing factorized terms with both index types

    # Returns
    `(structure, coefficient)` pairs with all factorizations unfolded.
    """

def list_dangling(self_: Expression) -> builtins.list[Expression]:
    r"""
    Lists the dangling (external, uncontracted) indices present in the expression.

    Identifies and returns all indices that are not summed over (i.e., not dummy
    indices). These are the "free" indices that appear in the final result and
    determine the tensor rank of the expression. For dualizable representations,
    downstairs indices are represented wrapped in `dind(...)`.

    This is essential for:
    - Verifying index conservation in tensor equations
    - Determining the rank and structure of tensor expressions
    - Debugging index contractions

    # Arguments
    - `self_`: tensor expression to analyze

    # Returns
    A list of expressions, each representing a free (dangling) index.

    # Examples:
    ```python
    from symbolica.community.spenso import TensorName, Slot, Representation
    import symbolica as sp
    from symbolica.community.idenso import (
        list_dangling,
    )

    T = TensorName("T")
    rep = Representation.euc(3)
    # With slots (creates TensorExpression)
    mu = rep("mu")
    nu = rep("nu")
    x = sp.S("x")
    tensor_with_args = T(x, mu, nu, nu)  # T(x; mu, nu, nu)
    # print(tensor_with_args)
    print(list_dangling(tensor_with_args.to_expression()))
    ```
    """

def metric_shorthand_to_dot(expression: Expression) -> Expression: ...
def normalize_chains(expression: Expression) -> Expression: ...
def normalize_dots(expression: Expression) -> Expression: ...
def schoonschip(
    expression: Expression, settings: typing.Optional[SchoonschipSettings] = None
) -> Expression: ...
def schoonschip_net(
    expression: Expression,
    settings: typing.Optional[SchoonschipSettings] = None,
    *,
    expand_contracted_sums: builtins.bool = ...,
) -> Expression: ...
def simplify_color(
    self_: Expression, settings: typing.Optional[ColorSimplifySettings] = None
) -> Expression:
    r"""
    Applies SU(N) color algebra rules to simplify color group structures.

    Performs comprehensive simplifications of SU(N) color algebra including:

    **Structure constants:**
    - Contractions expressed through the adjoint representation's Casimir
    - Antisymmetry and Jacobi identities
    - Antisymmetry: `f^{abc} = -f^{bac}`

    **Generators and traces:**
    - Generator traces expressed through the representation's Dynkin index
    - Fierz identities using the supplied fundamental and adjoint dimensions
    - Generator squares expressed through the representation's Casimir

    **Representation invariants:**
    Use `Representation.dimension`, `.casimir()`, `.dynkin_index()`, and `.gram(...)`
    to construct the scalar invariants associated with explicitly typed color structures.

    # Arguments
    - `self_`: expression containing SU(N) color structures

    # Returns
    Simplified expression with color algebra reduced to representation-owned scalar
    invariants when possible.

    # Notes
    If explicit color indices remain after simplification, it indicates the expression
    could not be fully reduced to color-scalar form.
    """

def simplify_epsilon(expression: Expression) -> Expression: ...
def simplify_gamma(
    self_: Expression, settings: typing.Optional[GammaSimplifySettings] = None
) -> Expression:
    r"""
    Applies Clifford algebra rules and trace identities to simplify gamma matrix expressions.

    Performs comprehensive simplifications of Dirac gamma matrix algebra including:
    - **Anticommutation relations**: `{γᵘ, γᵛ} = 2gᵘᵛ`
    - **Trace identities**: `Tr(γᵘ) = 0`, `Tr(γᵘγᵛ) = 4gᵘᵛ`, etc.
    - **Gamma5 properties**: `{γ₅, γᵘ} = 0`, `(γ₅)² = 1`
    - **Chain simplifications**: Reduces products of gamma matrices
    - **Contraction rules**: Simplifies contracted gamma matrix products

    The function recognizes gamma matrices represented as `spenso::gamma(spenso::mink(dim,mu), spenso::bis(dim,alpha), spenso::bis(dim,beta))`
    where `mu` is the Lorentz index and `alpha`, `beta` are spinor indices.
    These can be easily created using the hep_lib.

    # Arguments
    - `self_`: expression containing gamma matrix products and traces

    # Returns
    The simplified expression with gamma algebra applied.

    # Examples:
    ```python
    from symbolica.community.spenso import TensorLibrary, TensorName
    from symbolica.community.idenso import simplify_gamma
    from symbolica import S, Expression
    # Get HEP library with standard tensors
    hep_lib = TensorLibrary.hep_lib()
    # Access standard tensors like gamma matrices
    gamma_structure = hep_lib[S("spenso::gamma")]
    print(gamma_structure)
    print(simplify_gamma(gamma_structure(7, 3, 4) * gamma_structure(3, 7, 4)))
    ```
    """

def simplify_gamma0(expression: Expression) -> Expression: ...
def simplify_gamma_conjugate(expression: Expression) -> Expression: ...
def simplify_metrics(self_: Expression) -> Expression:
    r"""
    Simplifies contractions involving metric tensors and identity tensors.

    Applies fundamental tensor algebra rules for metric and identity tensors:

    **Metric tensor rules:**
    - `gᵘᵛ pᵥ → pᵘ` (index raising/lowering)
    - `gᵘᵛ gᵥρ → gᵘρ` or `δᵘρ` (metric composition)
    - `gᵘᵤ → D` (dimension of spacetime)
    - `ηᵘᵛ pᵥ → pᵘ` (flat metric contractions)

    **Identity tensor rules:**
    - `δᵘᵛ pᵥ → pᵘ` (Kronecker delta contraction)
    - `δᵘᵤ → D` (trace of identity)

    The function recognizes metrics as `spenso::g(...)`

    # Arguments
    - `self_`: expression containing metric/identity tensor contractions

    # Returns
    The simplified expression with metric rules applied.

    # Examples:
    ```python
    from symbolica.community.idenso import simplify_metrics, to_dots
    from symbolica.community.spenso import Representation, TensorName
    q = TensorName("q")
    g = TensorName.g()
    rep = Representation.euc(3)
    # With slots (creates TensorExpression)
    mu = rep("mu")
    nu = rep("nu")
    print(simplify_metrics(g(mu, nu) * q(mu)))
    ```
    """

def spenso_conjugate(expression: Expression) -> Expression: ...
def to_cof_dimension_invariants(expression: Expression) -> Expression: ...
def to_color_casimir(
    expression: Expression,
    *,
    fundamental: Representation | Expression,
    adjoint: Representation | Expression,
    settings: typing.Optional[ColorCasimirSettings] = None,
) -> Expression: ...
def to_dots(self_: Expression) -> Expression:
    r"""
    Converts contracted Lorentz/Minkowski indices into dot product notation.

    Automatically identifies and converts patterns like `p(mink(D, mu)) * q(mink(D, mu))`
    into the compact, representation-carrying `dot(p(mink(D)), q(mink(D)))` notation. This
    simplification is essential for physics calculations involving four-vectors.

    The function recognizes:
    - Contracted vector indices: `pᵘqᵤ → p·q`
    - Multiple contractions: `pᵘqᵤrᵛsᵥ → (p·q)(r·s)`
    - Self-contractions: `pᵘpᵤ → p²`

    # Arguments
    - `self_`: expression containing contracted Minkowski vector indices

    # Returns
    The expression with vector contractions converted to dot products.

    # Examples:
    ```python
    from symbolica.community.idenso import to_dots
    from symbolica.community.spenso import Representation, TensorName
    p = TensorName("p")
    q = TensorName("q")
    rep = Representation.euc(3)
    # With slots (creates TensorExpression)
    mu = rep("mu")
    nu = rep("nu")

    print(to_dots( p(mu)*q(mu)))
    ```
    """

def uncook(
    expression: Expression, settings: typing.Optional[CookSettings] = None
) -> Expression: ...
def undo_all(expression: Expression) -> Expression: ...
def undo_chain(expression: Expression) -> Expression: ...
def undo_dots(expression: Expression) -> Expression: ...
def undo_schoonschip(expression: Expression) -> Expression: ...
def undo_single_length(expression: Expression) -> Expression: ...
def undo_trace(expression: Expression) -> Expression: ...
def wrap_color(expression: Expression, symbol: Expression) -> Expression: ...
def wrap_dummies(self_: Expression, header: Expression) -> Expression:
    r"""
    Wraps only the dummy (contracted) indices within the expression using a header symbol.

    Similar to `wrap_indices`, but selectively identifies and wraps only contracted
    indices (those appearing once upstairs and once downstairs, or twice in a
    self-dual representation), leaving external (dangling) indices untouched.
    This is crucial for proper index management in tensor calculations.

    Contracted indices are those that:
    - Appear in both upper and lower positions (for dualizable reps)
    - Appear twice in the same position (for self-dual reps)
    - Are summed over (Einstein summation convention)

    # Arguments
    - `self_`: input expression containing both dummy and free indices
    - `header`: symbol to use as wrapper function name for dummy indices only

    # Returns
    A new expression with only contracted indices wrapped.

    # Examples:
    ```python
    from symbolica.community.spenso import TensorName, Slot, Representation
    import symbolica as sp
    from symbolica.community.idenso import simplify_metrics, wrap_dummies

    T = TensorName("T")
    rep = Representation.euc(3)
    # With slots (creates TensorExpression)
    mu = rep("mu")
    nu = rep("nu")
    x = sp.S("x")
    tensor_with_args = T(x, mu, nu, nu)  # T(x; mu, nu, nu)
    # print(tensor_with_args)
    print(wrap_dummies(tensor_with_args.to_expression(), sp.S("wrap")))

    ```
    """

def wrap_indices(self_: Expression, header: Expression) -> Expression:
    r"""
    Wrap all abstract indices with a header symbol

    # Arguments
    - `self_`: input expression containing tensor indices
    - `header`: symbol to use as the wrapper function for all indices

    # Returns
    Expression with all indices wrapped by the header symbol.

    # Examples:
    ```python
    from symbolica.community.spenso import TensorName, Slot, Representation
    import symbolica as sp
    from symbolica.community.idenso import wrap_indices

    T = TensorName("T")
    rep = Representation.euc(3)
    # With slots (creates TensorExpression)
    mu = rep("mu")
    nu = rep("nu")
    x = sp.S("x")
    tensor_with_args = T(x, mu, nu)  # T(x; mu, nu)
    print(tensor_with_args)
    print(wrap_indices(tensor_with_args.to_expression(), sp.S("wrap")))

    ```
    """
